Some debian package manager tweaks
census-instrumentation/opencensus-cpp pull request #435
Opened 2020-03-04 13:50 UTC by Rajpratik71

By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages . 

By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.

This results in smaller downloads and installation of packages .

Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .

results in smaller image size.

2020-03-11 07:31 UTC, g-easy commented
How much does it save?

2020-03-11 07:31 UTC, g-easy commented on tools/docker-format/Dockerfile
> +RUN apt-get update && \
Please change back to just "apt"

2022-01-23 12:53 UTC, Kaosha40 commented on tools/docker-format/Dockerfile
> +RUN apt-get update && \
Okay

2022-03-16 06:33 UTC, lgruen requested changes
Sorry, I'm not working on OpenCensus anymore, but can't remove myself as a reviewer from this PR. Dismissing this review using "request changes" might remove it from my PR queue though.

2022-03-16 11:20 UTC, closed without merging